# NAME: BOYA SHILPA

# Problem statement: Create a classification model to type of the Date Fruits based on external appearance features provided in the dataset


# DECISION TREE CLASSIFICATION

## Step 1: Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Step 2: Importing data and exploring data

In [3]:
df=pd.read_excel('Date_fruits_dataset.xlsx')
df.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0  422163   2378.908    837.8484    645.6693        0.6373  733.1539   
1  338136   2085.144    723.8198    595.2073        0.5690  656.1464   
2  526843   2647.394    940.7379    715.3638        0.6494  819.0222   
3  416063   2351.210    827.9804    645.2988        0.6266  727.8378   
4  347562   2160.354    763.9877    582.8359        0.6465  665.2291   

   SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0    0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1    0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2    0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3    0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4    0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   

   KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  ALLdaub4RG  \
0      4.2287 -59191263232 -50714214400 -39922372608     58.7255     54.9554   
1      3.1704 -34233065472 -37462601728 -31477794816     50.0259     52.8168   
2      4.7192 -93948354560 -74738221056 -60311207936     65.4772     59.2860   
3      8.2618 -32074307584 -32060925952 -29575010304     43.3900     44.1259   
4      4.4146 -39980974080 -35980042240 -25593278464     52.7743     50.9080   

   ALLdaub4RB  Class  
0     47.8400  BERHI  
1     47.8315  BERHI  
2     51.9378  BERHI  
3     41.1882  BERHI  
4     42.6666  BERHI  

[5 rows x 35 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   AREA           898 non-null    int64  
 1   PERIMETER      898 non-null    float64
 2   MAJOR_AXIS     898 non-null    float64
 3   MINOR_AXIS     898 non-null    float64
 4   ECCENTRICITY   898 non-null    float64
 5   EQDIASQ        898 non-null    float64
 6   SOLIDITY       898 non-null    float64
 7   CONVEX_AREA    898 non-null    int64  
 8   EXTENT         898 non-null    float64
 9   ASPECT_RATIO   898 non-null    float64
 10  ROUNDNESS      898 non-null    float64
 11  COMPACTNESS    898 non-null    float64
 12  SHAPEFACTOR_1  898 non-null    float64
 13  SHAPEFACTOR_2  898 non-null    float64
 14  SHAPEFACTOR_3  898 non-null    float64
 15  SHAPEFACTOR_4  898 non-null    float64
 16  MeanRR         898 non-null    float64
 17  MeanRG         898 non-null    float64
 18  MeanRB    

In [5]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [6]:
df.dtypes

AREA               int64
PERIMETER        float64
MAJOR_AXIS       float64
MINOR_AXIS       float64
ECCENTRICITY     float64
EQDIASQ          float64
SOLIDITY         float64
CONVEX_AREA        int64
EXTENT           float64
ASPECT_RATIO     float64
ROUNDNESS        float64
COMPACTNESS      float64
SHAPEFACTOR_1    float64
SHAPEFACTOR_2    float64
SHAPEFACTOR_3    float64
SHAPEFACTOR_4    float64
MeanRR           float64
MeanRG           float64
MeanRB           float64
StdDevRR         float64
StdDevRG         float64
StdDevRB         float64
SkewRR           float64
SkewRG           float64
SkewRB           float64
KurtosisRR       float64
KurtosisRG       float64
KurtosisRB       float64
EntropyRR          int64
EntropyRG          int64
EntropyRB          int64
ALLdaub4RR       float64
ALLdaub4RG       float64
ALLdaub4RB       float64
Class             object
dtype: object

In [7]:
df['Class'].value_counts()

DOKOL     204
SAFAVI    199
ROTANA    166
DEGLET     98
SOGAY      94
IRAQI      72
BERHI      65
Name: Class, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb=LabelEncoder()

In [10]:
df['Class']=lb.fit_transform(df['Class'])

In [11]:
df['Class'].value_counts()

2    204
5    199
4    166
1     98
6     94
3     72
0     65
Name: Class, dtype: int64

## Step 3: Alloting data to x and y variables

In [12]:
x=df[['AREA', 'PERIMETER', 'MAJOR_AXIS', 'MINOR_AXIS', 'ECCENTRICITY',
       'EQDIASQ', 'SOLIDITY', 'CONVEX_AREA', 'EXTENT', 'ASPECT_RATIO',
       'ROUNDNESS', 'COMPACTNESS', 'SHAPEFACTOR_1', 'SHAPEFACTOR_2',
       'SHAPEFACTOR_3', 'SHAPEFACTOR_4', 'MeanRR', 'MeanRG', 'MeanRB',
       'StdDevRR', 'StdDevRG', 'StdDevRB', 'SkewRR', 'SkewRG', 'SkewRB',
       'KurtosisRR', 'KurtosisRG', 'KurtosisRB', 'EntropyRR', 'EntropyRG',
       'EntropyRB', 'ALLdaub4RR', 'ALLdaub4RG', 'ALLdaub4RB']]
y=df['Class']
print(x.shape,y.shape)

(898, 34) (898,)


In [13]:
x.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0  422163   2378.908    837.8484    645.6693        0.6373  733.1539   
1  338136   2085.144    723.8198    595.2073        0.5690  656.1464   
2  526843   2647.394    940.7379    715.3638        0.6494  819.0222   
3  416063   2351.210    827.9804    645.2988        0.6266  727.8378   
4  347562   2160.354    763.9877    582.8359        0.6465  665.2291   

   SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  SkewRB  KurtosisRR  \
0    0.9947       424428  0.7831        1.2976  ...  0.6019      3.2370   
1    0.9974       339014  0.7795        1.2161  ...  0.4134      2.6228   
2    0.9962       528876  0.7657        1.3150  ...  0.9183      3.7516   
3    0.9948       418255  0.7759        1.2831  ...  1.8028      5.0401   
4    0.9908       350797  0.7569        1.3108  ...  0.8865      2.7016   

   KurtosisRG  KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  \
0      2.9574      4.2287 -59191263232 -50714214400 -39922372608     58.7255   
1      2.6350      3.1704 -34233065472 -37462601728 -31477794816     50.0259   
2      3.8611      4.7192 -93948354560 -74738221056 -60311207936     65.4772   
3      8.6136      8.2618 -32074307584 -32060925952 -29575010304     43.3900   
4      2.9761      4.4146 -39980974080 -35980042240 -25593278464     52.7743   

   ALLdaub4RG  ALLdaub4RB  
0     54.9554     47.8400  
1     52.8168     47.8315  
2     59.2860     51.9378  
3     44.1259     41.1882  
4     50.9080     42.6666  

[5 rows x 34 columns]

In [14]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int32

In [15]:
print(type(x),type(y))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>


## Step 4: Splitting data into training and testing data

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(673, 34)
(225, 34)
(673,)
(225,)


## Step 5: Building the model

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
dtree=DecisionTreeClassifier()

In [20]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
predictions=dtree.predict(x_test)

# Printing the predicted type of Date fruits for test data

In [22]:
pdf=pd.DataFrame(predictions,y_test,columns=['predictions'])

In [23]:
pdf

predictions
Class             
1                1
3                3
4                0
3                3
0                3
...            ...
1                2
1                1
6                6
5                5
4                4

[225 rows x 1 columns]

## Step 6: Evaluating model i.e., calculating confusion_matrix & classification_report

In [24]:
from sklearn.metrics import confusion_matrix,classification_report

In [25]:
print(confusion_matrix(y_test,predictions))

[[ 3  0  0  4  0  0  1]
 [ 0 14  3  0  0  1  5]
 [ 0  2 51  0  0  1  0]
 [ 2  0  0 16  0  1  0]
 [ 3  0  1  1 38  0  0]
 [ 0  0  0  0  0 55  0]
 [ 0  4  0  1  0  0 18]]


In [26]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.38      0.38      0.38         8
           1       0.70      0.61      0.65        23
           2       0.93      0.94      0.94        54
           3       0.73      0.84      0.78        19
           4       1.00      0.88      0.94        43
           5       0.95      1.00      0.97        55
           6       0.75      0.78      0.77        23

    accuracy                           0.87       225
   macro avg       0.78      0.78      0.77       225
weighted avg       0.87      0.87      0.87       225



# RANDOM FOREST CLASSIFICATION

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rfc= RandomForestClassifier(n_estimators=200)

In [29]:
rfc.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [30]:
rfc_pred=rfc.predict(x_test)

# Printing the predicted type of Date fruits for test data

In [31]:
pdf1=pd.DataFrame(rfc_pred,y_test,columns=['predictions'])

In [32]:
pdf1

predictions
Class             
1                1
3                3
4                4
3                3
0                4
...            ...
1                1
1                1
6                6
5                5
4                4

[225 rows x 1 columns]

## calculating confusion_matrix & classification_report for RFC

In [33]:
print(confusion_matrix(y_test,rfc_pred))

[[ 5  0  0  2  1  0  0]
 [ 0 16  1  0  0  0  6]
 [ 0  0 54  0  0  0  0]
 [ 2  0  0 16  1  0  0]
 [ 0  1  0  0 41  0  1]
 [ 0  0  0  0  0 55  0]
 [ 0  5  0  0  0  1 17]]


In [34]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.73      0.70      0.71        23
           2       0.98      1.00      0.99        54
           3       0.89      0.84      0.86        19
           4       0.95      0.95      0.95        43
           5       0.98      1.00      0.99        55
           6       0.71      0.74      0.72        23

    accuracy                           0.91       225
   macro avg       0.85      0.84      0.84       225
weighted avg       0.91      0.91      0.91       225



# KNN CLASSIFICATION

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
m2=KNeighborsClassifier(n_neighbors=19)

In [37]:
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=19)

In [38]:
knn_pred=m2.predict(x_test)

# Printing the predicted type of Date fruits for test data

In [39]:
pdf2=pd.DataFrame(knn_pred,y_test,columns=['predictions'])

In [40]:
pdf2

predictions
Class             
1                2
3                0
4                4
3                2
0                4
...            ...
1                1
1                4
6                1
5                5
4                4

[225 rows x 1 columns]

## calculating confusion_matrix & classification_report for KNN

In [41]:
print(confusion_matrix(y_test,knn_pred))

[[ 0  2  2  1  3  0  0]
 [ 1  8  7  1  2  0  4]
 [ 1  3 47  0  0  3  0]
 [ 2  3  5  6  2  1  0]
 [ 0  1  0  2 40  0  0]
 [ 0  0  1  0  0 54  0]
 [ 2  6  5  0  2  1  7]]


In [42]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.35      0.35      0.35        23
           2       0.70      0.87      0.78        54
           3       0.60      0.32      0.41        19
           4       0.82      0.93      0.87        43
           5       0.92      0.98      0.95        55
           6       0.64      0.30      0.41        23

    accuracy                           0.72       225
   macro avg       0.57      0.54      0.54       225
weighted avg       0.70      0.72      0.70       225



# LOGISTIC REGRESSION

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
lor=LogisticRegression()

In [45]:
lor.fit(x_train,y_train)

LogisticRegression()

In [46]:
lor_pred=lor.predict(x_test)

# Printing the predicted type of Date fruits for test data


In [47]:
pdf3=pd.DataFrame(lor_pred,y_test,columns=['predictions'])

In [48]:
pdf3

predictions
Class             
1                2
3                3
4                4
3                3
0                3
...            ...
1                2
1                4
6                4
5                5
4                4

[225 rows x 1 columns]

## calculating confusion_matrix & classification_report for LogisticRegression

In [49]:
print(confusion_matrix(y_test,lor_pred))

[[ 0  0  1  2  5  0  0]
 [ 0  0  3  0 12  1  7]
 [ 0  0 25  4 22  1  2]
 [ 0  0  0 11  5  3  0]
 [ 0  0  2  0 40  0  1]
 [ 0  0  0  4  0 51  0]
 [ 0  0  0  0 15  1  7]]


In [50]:
print(classification_report(y_test,lor_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.00      0.00      0.00        23
           2       0.81      0.46      0.59        54
           3       0.52      0.58      0.55        19
           4       0.40      0.93      0.56        43
           5       0.89      0.93      0.91        55
           6       0.41      0.30      0.35        23

    accuracy                           0.60       225
   macro avg       0.43      0.46      0.42       225
weighted avg       0.58      0.60      0.55       225



# CROSS VALIDATION

In [73]:
from sklearn.model_selection import cross_val_score

In [74]:
lor_cv=cross_val_score(LogisticRegression(),x,y)


In [75]:
rfc_cv=cross_val_score(RandomForestClassifier(),x,y)

In [76]:
knc_cv=cross_val_score(KNeighborsClassifier(),x,y)

In [77]:
dtc_cv=cross_val_score(DecisionTreeClassifier(),x,y)

In [78]:
print('lor_cv',':',lor_cv.mean())
print('rfc_cv',':',rfc_cv.mean())
print('knc_cv',':',knc_cv.mean())
print('dtc_cv',':',dtc_cv.mean())

lor_cv : 0.5467101179391682
rfc_cv : 0.8864245810055866
knc_cv : 0.677008069522036
dtc_cv : 0.8462693978895096


# The model with best accuracy is Random Forest Classification because it has high cross validation value i.e.,0.89  approximately comparing with other models